DROP SEQUENCE BOARDNOSEQ;
DROP SEQUENCE GROUPNOSEQ;

DROP TABLE ANSWERBOARD;

CREATE SEQUENCE BOARDNOSEQ;
CREATE SEQUENCE GROUPNOSEQ;

CREATE TABLE ANSWERBOARD(
BOARDNO NUMBER PRIMARY KEY,
GROUPNO NUMBER NOT NULL,
GROUPSEQ NUMBER NOT NULL,
TITLETAB NUMBER NOT NULL,
DELFLAG VARCHAR(2) NOT NULL,
TITLE VARCHAR(1000) NOT NULL,
CONTENT VARCHAR(3000) NOT NULL,
WRITER VARCHAR(200) NOT NULL,
REGDATE DATE NOT NULL,
CONSTRAINT ANSWER_CK_DELFLAG CHECK (DELFLAG IN('Y','N')) -- N:삭제된 글입니다. 
);


--1ST WRITE  
INSERT INTO ANSWERBOARD
VALUES(BOARDNOSEQ.NEXTVAL,
        GROUPNOSEQ.NEXTVAL,
        1,
        0,
        'N',
        '제목입니다.',
        '내용입니다.',
        '작성자이다.',
        SYSDATE
        );
        
        
        
--선택 
SELECT BOARDNO, GROUPNO, GROUPSEQ, TITLETAB, DELFLAG, TITLE, CONTENT, WRITER ,REGDATE
FROM ANSWERBOARD
ORDER BY GROUPNO DESC, GROUPSEQ;
 





