DROP SEQUENCE MDBOARDSEQ;
DROP TABLE MDBOARD;

CREATE SEQUENCE MDBOARDSEQ; ----[1] 시퀀스 테이블 만들고 
-- SEQUENCE :자동으로 순차적으로 증가하는 순번을 반환하는 DB객체  

CREATE TABLE MDBOARD(
  SEQ NUMBER PRIMARY KEY,
  WRITER VARCHAR2(100) NOT NULL,
  TITLE VARCHAR2(1000) NOT NULL,
  CONTENT VARCHAR2(4000) NOT NULL,
  REGDATE DATE NOT NULL
);


INSERT INTO MDBOARD----[2]MDBOARDSEQ.NEXTVA 을 설정해주면 순차적으로 증가하는 일종의 일련번호가 생김 . 
VALUES(MDBOARDSEQ.NEXTVAL,'관리자','MVC재밋어요','열심히하세요',SYSDATE);

SELECT SEQ, WRITER,TITLE, CONTENT, REGDATE
FROM MDBOARD
ORDER BY SEQ DESC;